name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.4.2
      - run: npm ci
      - run: npm run test:build
      - name: api
        run: npm run test:api
      - name: e2e
        run: npm run test:vue
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.4.2
      - run: npm ci
      - name: vue-tsc
        run: npx vue-tsc --noEmit
      - name: eslint
        run: npm run lint
