name: Continuous Integration

on:
  push:
    branches: [ 26-set-up-continuous-integration ]

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - run: npm ci
      - run: npm run build
      - run: npm run test
