name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: build
        run: npm run test:build
      - name: bash
        run: npm run test:bash
      - name: api
        run: npm run test:api
      - name: e2e
        run: npm run test:vue
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/coverage/merged/cobertura-coverage.xml
          verbose: true
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: vue-tsc
        run: npx vue-tsc --noEmit
